# Generated by Django 5.1.6 on 2025-02-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNames',
        ),
    ]
